# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
login:
  url: /login
  param: { module:sfGuardAuth, action:singin}

#sf_guard_signout:
#  url: /logout
#  param: {module: sfGuardAuth, action:signout}

#sf_guard_password:
#  url: /request_password
#  param: {module:sfGuardAuth, action:password}

#sf_guard_register:
#  url: /registro
#  param: {module:sfGuardRegister, action:index}

#sf_guard_forgot_password:
#   url: /forgot
#   param: {module: sfGuardForgotPassword, action:index}
   

user_logout:
  url:   /logout
  param: { module: evento, action: logout}

libro:
  url:   /libro
  param: { module: evento, action: libro}

new:
  url:   /new
  param: { module: evento, action: new}

gramatica:
  url:   /gramatica
  param: { module: evento1, action: gramatica}

pornivel:
  url:   /gramatica/nivel/:nivel
  param: { module: evento1, action: pornivel}
  
homepage:
  url:   /
  param: { module: evento, action: index }

# generic rules
# please, remove them by adding more specific rules

 


libroform: #para el formulario
  url: /libroform
  param: {module:home, action:prueba}
  
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


