<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/18 12:32:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=paloma',
  'username' => 'paloma',
  'password' => 'paloma',
  'name' => 'doctrine',
)),);
