<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/18 12:32:59
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
