<?php

/**
 * GramaticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GramaticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GramaticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gramatica');
    }
	
	public function getAll()
	{
		return $this->createQuery('a')->execute();//con esto sacatodo de la tabla libro
		
	}
	
	public function getPorNivel($ni)
	{
		return $this->createQuery('a')->where('a.nivel=?',array($ni))->execute();//con esto sacatodo de la tabla libro
		
	}
}