<?php

/**
 * LibroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Libro');
    }
		
	public function getAll()
	{
		return $this->createQuery('a')->execute();//con esto sacatodo de la tabla libro
		
	}
}