<?php

/**
 * VocabularioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VocabularioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VocabularioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vocabulario');
    }
}