<?php

/**
 * BaseGramatica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $idioma
 * @property integer $nivel
 * @property string $enunciado
 * @property string $solucion
 * @property string $explicacion
 * 
 * @method string    getNombre()      Returns the current record's "nombre" value
 * @method string    getIdioma()      Returns the current record's "idioma" value
 * @method integer   getNivel()       Returns the current record's "nivel" value
 * @method string    getEnunciado()   Returns the current record's "enunciado" value
 * @method string    getSolucion()    Returns the current record's "solucion" value
 * @method string    getExplicacion() Returns the current record's "explicacion" value
 * @method Gramatica setNombre()      Sets the current record's "nombre" value
 * @method Gramatica setIdioma()      Sets the current record's "idioma" value
 * @method Gramatica setNivel()       Sets the current record's "nivel" value
 * @method Gramatica setEnunciado()   Sets the current record's "enunciado" value
 * @method Gramatica setSolucion()    Sets the current record's "solucion" value
 * @method Gramatica setExplicacion() Sets the current record's "explicacion" value
 * 
 * @package    proyecto1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGramatica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gramatica');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('idioma', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nivel', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('enunciado', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('solucion', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('explicacion', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}