<?php

/**
 * BaseJuego
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $idioma
 * @property integer $nivel
 * @property string $ruta
 * 
 * @method string  getNombre() Returns the current record's "nombre" value
 * @method string  getIdioma() Returns the current record's "idioma" value
 * @method integer getNivel()  Returns the current record's "nivel" value
 * @method string  getRuta()   Returns the current record's "ruta" value
 * @method Juego   setNombre() Sets the current record's "nombre" value
 * @method Juego   setIdioma() Sets the current record's "idioma" value
 * @method Juego   setNivel()  Sets the current record's "nivel" value
 * @method Juego   setRuta()   Sets the current record's "ruta" value
 * 
 * @package    proyecto1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJuego extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('juego');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('idioma', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nivel', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ruta', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}