<?php

/**
 * BaseExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $idioma
 * @property integer $nivel
 * @property integer $id_ejercicio
 * 
 * @method string  getNombre()       Returns the current record's "nombre" value
 * @method string  getIdioma()       Returns the current record's "idioma" value
 * @method integer getNivel()        Returns the current record's "nivel" value
 * @method integer getIdEjercicio()  Returns the current record's "id_ejercicio" value
 * @method Examen  setNombre()       Sets the current record's "nombre" value
 * @method Examen  setIdioma()       Sets the current record's "idioma" value
 * @method Examen  setNivel()        Sets the current record's "nivel" value
 * @method Examen  setIdEjercicio()  Sets the current record's "id_ejercicio" value
 * 
 * @package    proyecto1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExamen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('examen');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('idioma', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nivel', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_ejercicio', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}