<?php

/**
 * BaseVocabulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $idioma
 * @property integer $nivel
 * @property string $palabra
 * @property string $traduccion
 * @property Doctrine_Collection $LibroVocabulario
 * 
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getIdioma()           Returns the current record's "idioma" value
 * @method integer             getNivel()            Returns the current record's "nivel" value
 * @method string              getPalabra()          Returns the current record's "palabra" value
 * @method string              getTraduccion()       Returns the current record's "traduccion" value
 * @method Doctrine_Collection getLibroVocabulario() Returns the current record's "LibroVocabulario" collection
 * @method Vocabulario         setNombre()           Sets the current record's "nombre" value
 * @method Vocabulario         setIdioma()           Sets the current record's "idioma" value
 * @method Vocabulario         setNivel()            Sets the current record's "nivel" value
 * @method Vocabulario         setPalabra()          Sets the current record's "palabra" value
 * @method Vocabulario         setTraduccion()       Sets the current record's "traduccion" value
 * @method Vocabulario         setLibroVocabulario() Sets the current record's "LibroVocabulario" collection
 * 
 * @package    proyecto1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVocabulario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vocabulario');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('idioma', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nivel', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('palabra', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('traduccion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Libro as LibroVocabulario', array(
             'local' => 'id',
             'foreign' => 'vocabulario_id'));
    }
}